### ISSUE TITLE
DroneKit Crashes on Android 8+

### ISSUE THREAD

**Issue by binloan** [DroidPlanner/3DRServices#488]
Following your example project once you call

```java
this.controlTower.connect(listener:this);
```

The app crashes with the following message:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.dronekit, PID: 8258
    android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=-2 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

Seems like you do not take care of the change behavior of `startForeground` in Android 8.

**Comment by binloan** [comment]
Duplicate of [482](https://github.com/dronekit/dronekit-android/issues/482) closed.
